# Site settings
title: Simon Zheng
description: 'Simon is from New York City and graduated from Stanford University with a BS/MS in Computer Science. He lives in New York City and works as a software engineer. He is interested in technology, education, languages, and volleyball and his goal is to use his skills make a difference in the world.'
url: 'simonzheng.github.io/'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Simon Zheng'
  email: simon@simonzheng.com
#  twitter_username: ximonsin
#  facebook_username: ninjah
  github_username:  simonzheng
  linkedin_username:  simonzheng

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
